[workspace]
members = ["projects/*"]
default-members = [
    "projects/prism-wasm",
    "projects/prism-yew",
    "projects/prism-dioxus",
    "projects/prism-preview",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
